server:
  port: 8080
  tomcat:
    max-http-header-size: 1048576

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eclipse_villas_db
    username: root
    password: 132468Cjl/
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 10MB
        file-size-threshold: 2KB

      security:
        jwt:
          secret-key: 4d7cc2ad4ec0b54d613018c8f356ac22469ed4469f4a32d72b9f96f3e48d80f2
          expire-length: 3600000

  logging:
    level:
      root: INFO
      org.springframework: DEBUG
    file:
      name: logs/spring-boot-application.log

